application: sketchophone
version: 1
runtime: python27
api_version: 1
threadsafe: false

libraries:
- name: jinja2
  version: 2.6

handlers:
- url: /(.*)\.(ico|png)
  static_files: \1.\2
  upload: (.*)\.(ico|png)

- url: /static
  static_dir: static
  secure: always

- url: .*
  script: main.py
  secure: always

- url: /cron/.*
  script: main.py
  login: admin

inbound_services:
- warmup

builtins:
- deferred: on