application: sketchophone
version: 1
runtime: python27
api_version: 1
threadsafe: false

libraries:
- name: jinja2
  version: 2.6

handlers:
- url: /static
  static_dir: static
  secure: always

- url: .*
  script: main.py
  secure: always

inbound_services:
- warmup

builtins:
- deferred: on