application: sketchophone
version: 1
runtime: python27
api_version: 1
threadsafe: false

libraries:
- name: jinja2
  version: 2.6

handlers:
- url: /favicon\.ico
  static_files: static/img/ico/favicon.ico
  upload: static/img/ico/favicon\.ico

- url: /robots\.txt
  static_files: static/files/robots.txt
  upload: static/files/robots\.txt

- url: /humans\.txt
  static_files: static/files/humans.txt
  upload: static/files/humans\.txt

- url: /apple-touch-icon(.*)\.png
  static_files: static/img/ico/apple/144.png
  upload: static/img/ico/apple/144\.png

- url: /(.*)\.(ico|png|jpg)
  static_files: \1.\2
  upload: (.*)\.(ico|png|jpg)

- url: /google24b84bd282bc9c5c.html
  static_files: static/html/google24b84bd282bc9c5c.html
  upload: static/html/google24b84bd282bc9c5c.html
  secure: optional

- url: /static
  static_dir: static
  secure: always

- url: /cron/.*
  script: main.app
  login: admin

- url: .*
  script: main.py
  secure: always

skip_files:
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*\.DS_Store
- static/less
- apps

inbound_services:
- warmup

builtins:
- remote_api: on
- deferred: on